//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPArchiveLink.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAPArchiveLink.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate cannot be recognized.
        /// </summary>
        internal static string CertificateCannotBeRecognized {
            get {
                return ResourceManager.GetString("CertificateCannotBeRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate published.
        /// </summary>
        internal static string CertificatePublished {
            get {
                return ResourceManager.GetString("CertificatePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component(s) created successfully..
        /// </summary>
        internal static string ComponentCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ComponentCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component {0} deleted successfully.
        /// </summary>
        internal static string ComponentDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ComponentDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component ID was not specified.
        /// </summary>
        internal static string ComponentIdNotSpecified {
            get {
                return ResourceManager.GetString("ComponentIdNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component {0} not found in document {1}.
        /// </summary>
        internal static string ComponentNotFoundInDocument {
            get {
                return ResourceManager.GetString("ComponentNotFoundInDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component(s) updated successfully..
        /// </summary>
        internal static string ComponentUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ComponentUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Document Content for MultiPart.
        /// </summary>
        internal static string CreatingDocumentContentMultiPart {
            get {
                return ResourceManager.GetString("CreatingDocumentContentMultiPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Document Content for Single Component.
        /// </summary>
        internal static string CreatingDocumentContentSingleComponent {
            get {
                return ResourceManager.GetString("CreatingDocumentContentSingleComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Info Metadata for MultiPart.
        /// </summary>
        internal static string CreatingInfoMetadataMultiPart {
            get {
                return ResourceManager.GetString("CreatingInfoMetadataMultiPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Info Metadata for Single Component.
        /// </summary>
        internal static string CreatingInfoMetadataSingleComponent {
            get {
                return ResourceManager.GetString("CreatingInfoMetadataSingleComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document {0} and all associated components deleted successfully.
        /// </summary>
        internal static string DocumentAndComponentsDeleted {
            get {
                return ResourceManager.GetString("DocumentAndComponentsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during search operation..
        /// </summary>
        internal static string ErrorDuringSearch {
            get {
                return ResourceManager.GetString("ErrorDuringSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving certificate..
        /// </summary>
        internal static string ErrorSavingCertificate {
            get {
                return ResourceManager.GetString("ErrorSavingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse certificate from byte array. AuthId: {0}.
        /// </summary>
        internal static string FailedToParseCertificate {
            get {
                return ResourceManager.GetString("FailedToParseCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save component file..
        /// </summary>
        internal static string FailedToSaveComponentFile {
            get {
                return ResourceManager.GetString("FailedToSaveComponentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fromOffset is beyond component length.
        /// </summary>
        internal static string FromOffsetBeyondComponentLength {
            get {
                return ResourceManager.GetString("FromOffsetBeyondComponentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Document stream.
        /// </summary>
        internal static string GetDocumentStream {
            get {
                return ResourceManager.GetString("GetDocumentStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid component found.
        /// </summary>
        internal static string NoValidComponentFound {
            get {
                return ResourceManager.GetString("NoValidComponentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offsets cannot be negative.
        /// </summary>
        internal static string OffsetsCannotBeNegative {
            get {
                return ResourceManager.GetString("OffsetsCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search text must not be empty..
        /// </summary>
        internal static string SearchTextMustNotBeEmpty {
            get {
                return ResourceManager.GetString("SearchTextMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream must be readable..
        /// </summary>
        internal static string StreamMustBeReadable {
            get {
                return ResourceManager.GetString("StreamMustBeReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported content type: {0}.
        /// </summary>
        internal static string UnsupportedContentType {
            get {
                return ResourceManager.GetString("UnsupportedContentType", resourceCulture);
            }
        }
    }
}
