using System.Text;
using System.Web;

namespace SAPArchiveLink
{
    public static class ALParameter
    {
        public const string VarAccessMode = "accessMode";
        public const string VarAppType = "appType";
        public const string VarAttribute = "attribute";
        public const string VarAuthId = "authId";
        public const string VarCacheServer = "cacheServer";
        public const string VarCaseSensitive = "caseSensitive";
        public const string VarDataSrcId = "dataSrcId";
        public const string VarCompId = "compId";
        public const string VarCompVers = "compVers";
        public const string VarCompView = "compView";
        public const string VarContRep = "contRep";
        public const string VarContRepRef = "contRepRef";
        public const string VarDigest = "digest";
        public const string VarDocId = "docId";
        public const string VarDocIdRef = "docIdRef";
        public const string VarDocProt = "docProt";
        public const string VarDomain = "domain";
        public const string VarExpiration = "expiration";
        public const string VarFlags = "flags";
        public const string VarForceHeader = "forceHeader";
        public const string VarForceMimeType = "forceMimeType";
        public const string VarFromOffset = "fromOffset";
        public const string VarFromColumn = "fromColumn";
        public const string VarHashAlg = "hashalg";
        public const string VarIpAddr = "ipaddr";
        public const string VarIxAppl = "ixAppl";
        public const string VarIxCheckSum = "ixCheckSum";
        public const string VarIxUser = "ixUser";
        public const string VarOrigId = "origId";
        public const string VarLocker = "locker";
        public const string VarForce = "force";
        public const string VarName = "name";
        public const string VarNo206Response = "no206Response";
        public const string VarNumResults = "numResults";
        public const string VarPasswd = "passwd";
        public const string VarPattern = "pattern";
        public const string VarPermissions = "permissions";
        public const string VarPoolName = "poolName";
        public const string VarPrefVolume = "prefVolume";
        public const string VarStorageTier = "storageTier";
        public const string VarPVersion = "pVersion";
        public const string VarRelPath = "relPath";
        public const string VarReset = "reset";
        public const string VarResultAs = "resultAs";
        public const string VarRetention = "retention";
        public const string VarRmsPi = "rmspi";
        public const string VarRmsNode = "rmsnode";
        public const string VarSecKey = "secKey";
        public const string VarStoreParam = "storeParam";
        public const string VarTargetContRep = "targetContRep";
        public const string VarTenantId = "tenantId";
        public const string VarTimeout = "timeout";
        public const string VarToOffset = "toOffset";
        public const string VarToColumn = "toColumn";
        public const string VarToken = "token";
        public const string VarUser = "user";
        public const string VarUserSys = "userSys";
        public const string VarVolName = "volName";
        public const string VarWbDocId = "wbdocid";
        public const string VarScanned = "scanPerformed";
        public const string VarComponent = "component";
        public const string VarDocVersion = "docVersion";
        public const string VarRendition = "rendition";
        public const string VarAccessToken = "accessToken";
        public const string VarAddOnMode = "addonMode";
        public const string VarViewerMode = "viewerMode";
        public const string VarRecType = "recType";
        public const string VarRecInfo = "recInfo";
        public const string VarVolId = "volId";
        public const string VarFileName = "fileName";
        public const string VarContentLength = "contentLen";
    }
}
